For review
mpds-io/visavis pull request #1
Opened 2022-12-21 12:17 UTC by PavelZubkov

2022-12-21 13:47 UTC, nin-jin requested changes

2022-12-21 13:47 UTC, nin-jin commented on matrix/matrix.view.css
> +rect.nonformer {
Лучше тут везде добавить имя модуля в качестве префикса, чтобы не свинячить глобально:

```
[visavis_matrix] rect.nonformer { ... }
```

2022-12-21 13:47 UTC, nin-jin commented on matrix/matrix.view.tree
> +				<= Side_right $mol_scroll
Думаю этот скролл тут лишний.

2022-12-21 13:47 UTC, nin-jin commented on matrix/matrix.view.tree
> +	file Object
Тут можно $mol_blob использовать.

2022-12-21 13:47 UTC, nin-jin commented on matrix/matrix.view.tree
> +					content / <= Nonformers $mol_check_box
Лучше переопределить `Content` - тогда и лишние паддинги уйдут и лишних элементов в дереве не будет.

2022-12-21 13:47 UTC, nin-jin commented on matrix/matrix.view.ts
> +	}
Может лучше описать это через $mol_data, чтобы файл валидировался? А то мало ли балалайка какая придёт.

2022-12-21 13:47 UTC, nin-jin commented on matrix/matrix.view.ts
> +		draw_cells(node: SVGElement, row: Matrix_cell[]) {
Тут точно не нужна мемоизация? Рендеринг довольно тяжёлый.

2022-12-21 16:43 UTC, blokhin commented
:+1: :+1: :+1:

2022-12-27 03:39 UTC, PavelZubkov commented on app/app.view.ts
> +		}
https://github.com/hyoo-ru/mam_mol/pull/520/files

2022-12-27 04:30 UTC, PavelZubkov commented on app/app.view.tree
> +									arg * file <= file_title* \
Сейчас старый файл с таким названием затирается, думаю добавлять индекс в конец, если имя уже занято [1], [2]

2022-12-27 04:47 UTC, PavelZubkov commented on app/app.view.ts
> +			return this.$.$mol_state_local.value( `${this}.history()`, next ) ?? []
при добавлении индексов к именам, их можно использовать как ключи

2022-12-28 12:08 UTC, PavelZubkov commented on matrix/matrix.view.tree
> +				<= Side_right $mol_scroll
там в эмбед режиме две штуки смогу с боку показывать, сразу контейнер сделал

или вопрос имено к $mol_scroll, а не $mol_view?

2022-12-28 14:22 UTC, PavelZubkov commented on matrix/matrix.view.ts
> +		draw_cells(node: SVGElement, row: Matrix_cell[]) {
там d3 рулит рендерингом, не заметил разницы с ней и без, можно оставить

2022-12-28 15:55 UTC, nin-jin commented
Подвалу бы тоже паддинга добавить.

2022-12-28 16:21 UTC, nin-jin approved these changes

2022-12-28 16:27 UTC, nin-jin commented
Ещё надо плейсхолдер убрать, а то справа дыркой торчит.

2022-12-29 08:53 UTC, PavelZubkov commented
поправил

2023-01-31 19:08 UTC, blokhin commented
Обновлённый `nonformers.js` в оригинальном репозитории имеет приоритет, так что конфликт легко разрешить.

2023-03-02 14:53 UTC, merged